# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dc_kkbox.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(635, 353)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lable_ACCOUNT = QtWidgets.QLabel(self.centralwidget)
        self.lable_ACCOUNT.setGeometry(QtCore.QRect(50, 40, 91, 31))
        self.lable_ACCOUNT.setObjectName("lable_ACCOUNT")
        self.label_DRIVER_NAME = QtWidgets.QLabel(self.centralwidget)
        self.label_DRIVER_NAME.setGeometry(QtCore.QRect(50, 160, 141, 31))
        self.label_DRIVER_NAME.setObjectName("label_DRIVER_NAME")
        self.pushButton_open_web_driver = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_open_web_driver.setGeometry(QtCore.QRect(50, 270, 251, 31))
        self.pushButton_open_web_driver.setObjectName("pushButton_open_web_driver")
        self.pushButton_Discord_hook_close = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Discord_hook_close.setGeometry(QtCore.QRect(340, 270, 261, 31))
        self.pushButton_Discord_hook_close.setObjectName("pushButton_Discord_hook_close")
        self.lineEdit_account = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_account.setGeometry(QtCore.QRect(200, 40, 401, 31))
        self.lineEdit_account.setObjectName("lineEdit_account")
        self.lineEdit_driver_name = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_driver_name.setGeometry(QtCore.QRect(200, 160, 401, 31))
        self.lineEdit_driver_name.setObjectName("lineEdit_driver_name")
        self.lineEdit_discord_client_id = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_discord_client_id.setGeometry(QtCore.QRect(200, 100, 401, 31))
        self.lineEdit_discord_client_id.setObjectName("lineEdit_discord_client_id")
        self.label_KKBOX_APP_SECRET_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_KKBOX_APP_SECRET_2.setGeometry(QtCore.QRect(50, 100, 141, 31))
        self.label_KKBOX_APP_SECRET_2.setObjectName("label_KKBOX_APP_SECRET_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 635, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "KKBOX Discord 豐富狀態"))
        self.lable_ACCOUNT.setText(_translate("MainWindow", "KKBOX 帳號"))
        self.label_DRIVER_NAME.setText(_translate("MainWindow", "DRIVER NAME"))
        self.pushButton_open_web_driver.setText(_translate("MainWindow", "開啟 KKBOX"))
        self.pushButton_Discord_hook_close.setText(_translate("MainWindow", "關閉 KKBOX"))
        self.lineEdit_account.setText(_translate("MainWindow", "TYPE_HERE_KKBOX_ACCOUNT"))
        self.lineEdit_driver_name.setText(_translate("MainWindow", "TYPE_HERE_DRIVER"))
        self.lineEdit_discord_client_id.setText(_translate("MainWindow", "TYPE_HERE_DISCORD_APPLICATION_ID"))
        self.label_KKBOX_APP_SECRET_2.setText(_translate("MainWindow", "APPLICATION ID"))
